name: Fast OCR Bot

on:
  push:
    paths:
      - 'link.txt'
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  run-fast-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 2  # Safety cutoff
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip' # Dependencies ko cache karega taki agli baar aur fast ho

      # System Libraries (Tesseract is faster than installing PyTorch)
      - name: Install System Libs
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg tesseract-ocr libtesseract-dev

      - name: Install Python Libs
        run: pip install -r requirements.txt

      - name: Run Script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        run: python main.py

      - name: Update History
        run: |
          git config --global user.name "Fast Bot"
          git config --global user.email "bot@github.com"
          git add history.txt
          git commit -m "Done" || echo "No changes"
          git push
