name: Insta Bypass Bot

on:
  push:
    paths:
      - 'link.txt'
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  run-bypass-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Install Tesseract
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y tesseract-ocr libtesseract-dev

      - name: Install Python Libs
        run: pip install -r requirements.txt

      - name: Run Script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        run: python main.py

      - name: Update History
        run: |
          git config --global user.name "Bypass Bot"
          git config --global user.email "bot@github.com"
          git add history.txt
          git commit -m "Processed Reel" || echo "No changes"
          git push
